mariadb5:
  image: "pcgeek/mariadb:5.5"
  volumes:
    - ./databases/mariadb/5.5:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

mariadb10:
  image: "pcgeek/mariadb:10"
  volumes:
    - ./databases/mariadb/10:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

php5.4-fpm:
  image: "pcgeek/php-fpm:5.4"
  volumes:
    - ./domains/sites:/var/www
    - ./environment/php/5.4/config/php.ini:/usr/local/etc/php/php.ini
  links:
    - mariadb5
    - mariadb10

php7-fpm:
  image: "pcgeek/php-fpm:7"
  volumes:
    - ./domains/sites:/var/www
    - ./environment/php/7/config/php.ini:/usr/local/etc/php/php.ini
  links:
    - mariadb5
    - mariadb10

apache:
  image: "pcgeek/apache:2.4"
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./domains/sites:/var/www
    - ./domains/vhosts:/usr/local/apache2/conf/vhosts
    - ./environment/apache/2.4/config/httpd.conf:/usr/local/apache2/conf/httpd.conf
  links:
    - php5.4-fpm
    - php7-fpm

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: myadmin
  environment:
  # - PMA_ARBITRARY=1
   - PMA_HOSTS=mariadb5,mariadb10
  restart: always
  ports:
   - 8080:80
  links:
    - mariadb5
    - mariadb10


